/**
 * Created by Denis on 25.02.2017.
 */
/* eslint-disable */
export default {
    users: 'Пользователи',
    models: 'Модели',
    'create': 'Создать',
    title: 'Название',
    keywords: 'Keywords',
    description: 'Описание',
    save: 'Сохранить',
    cancel: 'Отменить',
    mark:'Марка',
    marks:'Марки',
    model:'Модель',
    year:'Год',
    "enter new mark": 'Введите название марки',
    add: 'Добавить',
    close: 'Закрыть',
    edit: 'Редактировать',
    delete: 'Удалить',
    price: 'Цена',
    'header-title': 'Ваша админка',
    login: 'Пользователь',
    'input login': 'Введите имя',
    password: 'Пароль',
    'input password': 'Введите пароль',
    send: 'Отправить',
    administrator: 'Администратор',
    content_manager: 'Контент-менеджер',
    view: 'Просматривать',
    permissions: 'Права',
    present_type: 'Роли',
    admin: 'Администратор',
    content: 'Контент',
    properties: 'Свойства',
    not_enter: 'Не заполнено',
    incorrect: 'Не верное значение',
    insert_image: 'Вставить изображение',
    gallery: 'Галерея',
    name: "Имя",
    preview_image: 'Изображение',
    articles: 'Статьи'
}